<div id="hcard-Sebastian-Hoß" class="vcard">
 <a class="url fn" href="http://shoss.de">Sebastian Hoß</a>
 <a class="email" href="mailto:mail@shoss.de">mail@shoss.de</a>
 <div class="adr">
  <div class="street-address">Soester Straße 37/39</div>
  <span class="locality">Münster</span>, 
  <span class="region">NRW</span>, 
  <span class="postal-code">48149</span>
  <span class="country-name">Germany</span>
 </div>
 <a class="url" href="xmpp:sebihoss@jabber.ccc.de">Jabber</a>
</div>